name: Deploy Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm i
          pm2 start npm --name "github_action" -- run start
          pm2 save
          sudo service nginx restart
  run_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18, 19]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - run: |
          npm i
          echo "Tested ${{ matrix.node }}"
